// Frontend rendering boundary.
// Canvas code consumes this plain snapshot instead of the mutable Game instance,
// so future frontends can render the same domain state without inheriting Game internals.
export function createRenderState(game) {
  return {
    W: game.W,
    H: game.H,
    gameMode: game.gameMode || game.multiplayer?.mapMode || 'test',
    map: { ...game.map },
    camera: { ...game.camera },
    zones: game.zones,
    mapFeatures: game.mapFeatures || [],
    campaignArrival: game.campaignArrival ? { ...game.campaignArrival, path: Array.isArray(game.campaignArrival.path) ? game.campaignArrival.path.map(point => ({ ...point })) : game.campaignArrival.path } : null,
    rocks: game.rocks,
    holes: game.holes,
    trees: game.trees,
    hempPlants: game.hempPlants,
    items: game.items,
    structures: game.structures,
    monsters: game.monsters,
    projectiles: game.projectiles,
    bots: game.bots,
    player: game.player,
    assistant: game.assistant,
    placementType: game.placementType,
    zoneDraft: game.zoneDraft,
    mouse: { ...game.mouse },
    multiplayer: game.multiplayer,
    dayNight: typeof game.getDayNightState === 'function' ? game.getDayNightState() : game.dayNight,
    fogOfWar: game.fogOfWar,
    nightSpawns: game.nightSpawns,
    floaters: game.floaters,
    dynamicShadowsEnabled: !!game.dynamicShadowsEnabled,
    lightingEffectsEnabled: game.lightingEffectsEnabled !== false,
    showFpsOverlay: game.showFpsOverlay !== false,
    fps: game.fps || 0,
    targetFps: game.targetFps || 60,
    mobile: !!game.dom?.gameStage?.classList?.contains('is-mobile-device')
  };
}
